version: "{branch} (#{build})"

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  DEBUG: 1
  WARNINGS: 1
  matrix:
    - STANDALONE: 1
    - STANDALONE: 1
      CXXLATEST: 1
    - USING_BOOST: 1

for:
  -
    matrix:
      only:
        - image: Visual Studio 2013
    environment:
      BOOSTDIR: C:\Libraries\boost_1_58_0
    build_script:
      - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86
      - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
      - cd tests
      - nmake -f Makefile.msc
      - nmake -f Makefile.msc check
  -
    matrix:
      only:
        - image: Visual Studio 2015
    environment:
      BOOSTDIR: C:\Libraries\boost_1_63_0
    build_script:
      - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
      - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
      - cd tests
      - nmake -f Makefile.msc CPP11=1
      - nmake -f Makefile.msc CPP11=1 check
  -
    matrix:
      only:
        - image: Visual Studio 2017
    environment:
      BOOSTDIR: C:\Libraries\boost_1_69_0
      _WIN32_WINNT: 0x0603
    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
      - cd tests
      - nmake -f Makefile.msc CPP11=1 CPP14=1
      - nmake -f Makefile.msc CPP11=1 CPP14=1 check
  -
    matrix:
      only:
        - image: Visual Studio 2019
    environment:
      BOOSTDIR: C:\Libraries\boost_1_71_0
      _WIN32_WINNT: 0x0A00
    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
      - cd tests
      - nmake -f Makefile.msc CPP11=1 CPP14=1
      - nmake -f Makefile.msc CPP11=1 CPP14=1 check

matrix:
  exclude:
    - image: Visual Studio 2013
      CXXLATEST: 1
    - image: Visual Studio 2015
      CXXLATEST: 1
    - image: Visual Studio 2017
      CXXLATEST: 1
