language: cpp
sudo: false

#

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/boost_1_73_0

matrix:
  include:
    #
    #---------------------------------------------------------------------------
    # Linux / g++-9
    #---------------------------------------------------------------------------
    #
    # Linux / g++-9 -std=c++2a / -O2 / standalone
    #
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CXXFLAGS="-std=c++2a -Wall -Wextra -O2"
        - CONFIGFLAGS="--with-boost=no"
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"
      compiler: gcc
    #
    # Linux / g++-9 -std=c++14 / -O2 / boost 1.73
    #
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - BOOST_DIR="boost_1_73_0"
        - BOOST_URL="https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2"
        - CXXFLAGS="-std=c++14 -Wall -Wextra -O2"
        - CONFIGFLAGS="--with-boost=$PWD/$BOOST_DIR"
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"
      compiler: gcc
    #
    #---------------------------------------------------------------------------
    # Linux / g++-6
    #---------------------------------------------------------------------------
    #
    # Linux / g++-6 -std=c++11 / -O2 / standalone
    #
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CXXFLAGS="-std=c++11 -Wall -Wextra -O2"
        - CONFIGFLAGS="--with-boost=no"
        - MATRIX_EVAL="CC=gcc-6 CXX=g++-6"
      compiler: gcc
    #
    # Linux / g++-6 -std=c++03 / -O2 / boost 1.73
    #
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - BOOST_DIR="boost_1_73_0"
        - BOOST_URL="https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2"
        - CXXFLAGS="-std=c++03 -Wall -Wextra -O2"
        - CONFIGFLAGS="--with-boost=$PWD/$BOOST_DIR"
        - MATRIX_EVAL="CC=gcc-6 CXX=g++-6"
      compiler: gcc
    #
    #---------------------------------------------------------------------------
    # Linux / g++-4.9
    #---------------------------------------------------------------------------
    #
    # Linux / g++-4.9 -std=c++11 / -O2 / standalone
    #
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CXXFLAGS="-std=c++11 -Wall -Wextra -O2"
        - CONFIGFLAGS="--with-boost=no"
        - MATRIX_EVAL="CC=gcc-4.9 CXX=g++-4.9"
      compiler: gcc
    #
    # Linux / g++-4.9 -std=c++03 / -O2 / boost 1.73
    #
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - BOOST_DIR="boost_1_73_0"
        - BOOST_URL="https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2"
        - CXXFLAGS="-std=c++03 -Wall -Wextra -O2"
        - CONFIGFLAGS="--with-boost=$PWD/$BOOST_DIR"
        - MATRIX_EVAL="CC=gcc-4.9 CXX=g++-4.9"
      compiler: gcc
    #
    #---------------------------------------------------------------------------
    # Linux / clang-9 -std=c++2a
    #---------------------------------------------------------------------------
    #
    # Linux / clang-9 -std=c++2a / -O2 / standalone"
    #
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-9
          packages:
            - clang-9
      env:
        - CXXFLAGS="-std=c++14 -Wall -Wextra -O2"
        - CONFIGFLAGS="--with-boost=no"
        - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"
      compiler: clang
    #
    #---------------------------------------------------------------------------
    # Linux / clang-3.8
    #---------------------------------------------------------------------------
    #
    # Linux / clang-3.8 -std=c++11 / -O2 / standalone"
    #
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        - CXXFLAGS="-std=c++11 -Wall -Wextra -O2"
        - CONFIGFLAGS="--with-boost=no"
        - MATRIX_EVAL="CC=clang-3.8 CXX=clang++-3.8"
      compiler: clang
    #
    #---------------------------------------------------------------------------
    # macOS / xcode10.1
    #---------------------------------------------------------------------------
    #
    # macOS / xcode10.1 -std=c++14 / -O2 / standalone
    #
    - os: osx
      env:
        - CXXFLAGS="-std=c++14 -Wall -Wextra -O0 -fno-inline"
        - CONFIGFLAGS="--with-boost=no"
      osx_image: xcode10.1
    #
    # macOS / xcode10.1 -std=c++03 / -O2 / boost 1.73
    #
    - os: osx
      env:
        - BOOST_DIR="boost_1_73_0"
        - BOOST_URL="https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2"
        - CXXFLAGS="-std=c++03 -Wall -Wextra -O2"
        - CONFIGFLAGS="--with-boost=$PWD/$BOOST_DIR"
      osx_image: xcode10.1

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - |
    if [[ "${BOOST_URL}" != "" ]]; then
      if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
        { travis_retry wget --quiet -O - ${BOOST_URL} | tar -xj; } || exit 1
      fi
    fi

script:
  - ./autogen.sh && ./configure $CONFIGFLAGS && make && make check

notifications:
  email: false
