COMMON_CXXFLAGS = -nologo -GR -EHsc -I. -I../include

!ifdef CXXLATEST
STD_CXXFLAGS = -std:c++latest
!endif

!ifdef WARNINGS
WARNINGS_CXXFLAGS = -W4
!endif

!ifdef STATICRTL
! ifdef DEBUG
DEBUG_CXXFLAGS = -Zi -MTd
! else
DEBUG_CXXFLAGS = -O2 -MT
! endif
!else
! ifdef DEBUG
DEBUG_CXXFLAGS = -Zi -MDd
! else
DEBUG_CXXFLAGS = -O2 -MD
! endif
!endif

CXXFLAGS = \
	$(STD_CXXFLAGS) \
	$(COMMON_CXXFLAGS) \
	$(WARNINGS_CXXFLAGS) \
	$(DEBUG_CXXFLAGS)

CPP03_TEST_EXES = \
	cpp03\query_free.exe \
	cpp03\query_member.exe \
	cpp03\query_static.exe \
	cpp03\can_query_free.exe \
	cpp03\can_query_member.exe \
	cpp03\can_query_static.exe \
	cpp03\can_query_unsupported.exe \
	cpp03\can_query_not_applicable_free.exe \
	cpp03\can_query_not_applicable_member.exe \
	cpp03\can_query_not_applicable_static.exe \
	cpp03\can_query_not_applicable_unsupported.exe \
	cpp03\require_concept_free.exe \
	cpp03\require_concept_member.exe \
	cpp03\require_concept_static.exe \
	cpp03\can_require_concept_free.exe \
	cpp03\can_require_concept_member.exe \
	cpp03\can_require_concept_static.exe \
	cpp03\can_require_concept_unsupported.exe \
	cpp03\can_require_concept_not_applicable_free.exe \
	cpp03\can_require_concept_not_applicable_member.exe \
	cpp03\can_require_concept_not_applicable_static.exe \
	cpp03\can_require_concept_not_applicable_unsupported.exe \
	cpp03\require_free.exe \
	cpp03\require_member.exe \
	cpp03\require_static.exe \
	cpp03\can_require_free.exe \
	cpp03\can_require_member.exe \
	cpp03\can_require_static.exe \
	cpp03\can_require_unsupported.exe \
	cpp03\can_require_not_applicable_free.exe \
	cpp03\can_require_not_applicable_member.exe \
	cpp03\can_require_not_applicable_static.exe \
	cpp03\can_require_not_applicable_unsupported.exe \
	cpp03\prefer_free.exe \
	cpp03\prefer_member.exe \
	cpp03\prefer_static.exe \
	cpp03\prefer_unsupported.exe \
	cpp03\can_prefer_free.exe \
	cpp03\can_prefer_member.exe \
	cpp03\can_prefer_static.exe \
	cpp03\can_prefer_unsupported.exe \
	cpp03\can_prefer_not_applicable_free.exe \
	cpp03\can_prefer_not_applicable_member.exe \
	cpp03\can_prefer_not_applicable_static.exe \
	cpp03\can_prefer_not_applicable_unsupported.exe \
	cpp03\can_prefer_not_preferable_free.exe \
	cpp03\can_prefer_not_preferable_member.exe \
  cpp03\can_prefer_not_preferable_static.exe \
	cpp03\can_prefer_not_preferable_unsupported.exe

!ifdef CPP11

CPP11_TEST_EXES = \
	cpp11\query_free.exe \
	cpp11\query_member.exe \
	cpp11\query_static.exe \
	cpp11\can_query_free.exe \
	cpp11\can_query_member.exe \
	cpp11\can_query_static.exe \
	cpp11\can_query_unsupported.exe \
	cpp11\can_query_not_applicable_free.exe \
	cpp11\can_query_not_applicable_member.exe \
	cpp11\can_query_not_applicable_static.exe \
	cpp11\can_query_not_applicable_unsupported.exe \
	cpp11\require_concept_free.exe \
	cpp11\require_concept_member.exe \
	cpp11\require_concept_static.exe \
	cpp11\can_require_concept_free.exe \
	cpp11\can_require_concept_member.exe \
	cpp11\can_require_concept_static.exe \
	cpp11\can_require_concept_unsupported.exe \
	cpp11\can_require_concept_not_applicable_free.exe \
	cpp11\can_require_concept_not_applicable_member.exe \
	cpp11\can_require_concept_not_applicable_static.exe \
	cpp11\can_require_concept_not_applicable_unsupported.exe \
	cpp11\require_free.exe \
	cpp11\require_member.exe \
	cpp11\require_static.exe \
	cpp11\can_require_free.exe \
	cpp11\can_require_member.exe \
	cpp11\can_require_static.exe \
	cpp11\can_require_unsupported.exe \
	cpp11\can_require_not_applicable_free.exe \
	cpp11\can_require_not_applicable_member.exe \
	cpp11\can_require_not_applicable_static.exe \
	cpp11\can_require_not_applicable_unsupported.exe \
	cpp11\prefer_free.exe \
	cpp11\prefer_member.exe \
	cpp11\prefer_static.exe \
	cpp11\prefer_unsupported.exe \
	cpp11\can_prefer_free.exe \
	cpp11\can_prefer_member.exe \
	cpp11\can_prefer_static.exe \
	cpp11\can_prefer_unsupported.exe \
	cpp11\can_prefer_not_applicable_free.exe \
	cpp11\can_prefer_not_applicable_member.exe \
	cpp11\can_prefer_not_applicable_static.exe \
	cpp11\can_prefer_not_applicable_unsupported.exe \
	cpp11\can_prefer_not_preferable_free.exe \
	cpp11\can_prefer_not_preferable_member.exe \
  cpp11\can_prefer_not_preferable_static.exe \
	cpp11\can_prefer_not_preferable_unsupported.exe

!endif

!ifdef CPP14

CPP14_TEST_EXES = \
	cpp14\query_free.exe \
	cpp14\query_member.exe \
	cpp14\query_static.exe \
	cpp14\can_query_free.exe \
	cpp14\can_query_member.exe \
	cpp14\can_query_static.exe \
	cpp14\can_query_unsupported.exe \
	cpp14\can_query_not_applicable_free.exe \
	cpp14\can_query_not_applicable_member.exe \
	cpp14\can_query_not_applicable_static.exe \
	cpp14\can_query_not_applicable_unsupported.exe \
	cpp14\require_concept_free.exe \
	cpp14\require_concept_member.exe \
	cpp14\require_concept_static.exe \
	cpp14\can_require_concept_free.exe \
	cpp14\can_require_concept_member.exe \
	cpp14\can_require_concept_static.exe \
	cpp14\can_require_concept_unsupported.exe \
	cpp14\can_require_concept_not_applicable_free.exe \
	cpp14\can_require_concept_not_applicable_member.exe \
	cpp14\can_require_concept_not_applicable_static.exe \
	cpp14\can_require_concept_not_applicable_unsupported.exe \
	cpp14\require_free.exe \
	cpp14\require_member.exe \
	cpp14\require_static.exe \
	cpp14\can_require_free.exe \
	cpp14\can_require_member.exe \
	cpp14\can_require_static.exe \
	cpp14\can_require_unsupported.exe \
	cpp14\can_require_not_applicable_free.exe \
	cpp14\can_require_not_applicable_member.exe \
	cpp14\can_require_not_applicable_static.exe \
	cpp14\can_require_not_applicable_unsupported.exe \
	cpp14\prefer_free.exe \
	cpp14\prefer_member.exe \
	cpp14\prefer_static.exe \
	cpp14\prefer_unsupported.exe \
	cpp14\can_prefer_free.exe \
	cpp14\can_prefer_member.exe \
	cpp14\can_prefer_static.exe \
	cpp14\can_prefer_unsupported.exe \
	cpp14\can_prefer_not_applicable_free.exe \
	cpp14\can_prefer_not_applicable_member.exe \
	cpp14\can_prefer_not_applicable_static.exe \
	cpp14\can_prefer_not_applicable_unsupported.exe \
	cpp14\can_prefer_not_preferable_free.exe \
	cpp14\can_prefer_not_preferable_member.exe \
  cpp14\can_prefer_not_preferable_static.exe \
	cpp14\can_prefer_not_preferable_unsupported.exe

!endif

TEST_EXES = \
	$(CPP03_TEST_EXES) \
	$(CPP11_TEST_EXES) \
	$(CPP14_TEST_EXES)

all: \
	$(TEST_EXES)

check: $(TEST_EXES)
	!@echo === Running $** === && $** && echo.

{cpp03}.cpp{cpp03}.exe:
	cl -Fe$@ -Fo$(<:.cpp=.obj) $(CXXFLAGS) $(DEFINES) $< $(LIBS) -link -opt:ref

{cpp11}.cpp{cpp11}.exe:
	cl -Fe$@ -Fo$(<:.cpp=.obj) $(CXXFLAGS) $(DEFINES) $< $(LIBS) -link -opt:ref

{cpp14}.cpp{cpp14}.exe:
	cl -Fe$@ -Fo$(<:.cpp=.obj) $(CXXFLAGS) $(DEFINES) $< $(LIBS) -link -opt:ref

clean:
	-del /q /s cpp03\*.exe
	-del /q /s cpp03\*.exe.manifest
	-del /q /s cpp03\*.exp
	-del /q /s cpp03\*.ilk
	-del /q /s cpp03\*.pdb
	-del /q /s cpp03\*.obj
	-del /q /s cpp11\*.exe
	-del /q /s cpp11\*.exe.manifest
	-del /q /s cpp11\*.exp
	-del /q /s cpp11\*.ilk
	-del /q /s cpp11\*.pdb
	-del /q /s cpp11\*.obj
	-del /q /s cpp14\*.exe
	-del /q /s cpp14\*.exe.manifest
	-del /q /s cpp14\*.exp
	-del /q /s cpp14\*.ilk
	-del /q /s cpp14\*.pdb
	-del /q /s cpp14\*.obj
	-del /q /s *.pdb
